### ISSUE TITLE
fn_setupAction.sqf life_fnc_getPlayerSide not defined ?

### ISSUE THREAD

**Issue by VanilleIce** [Ni1kko/FrameworkV2#10]
here I get an error message that the variable was not defined.

fn_setupAction.sqf line 11
private _side = player call life_fnc_getPlayerSide;

**Comment by Ni1kko** [comment]
OLD server side function from `fn_preInit.sqf` 

 ```
 life_fnc_getPlayerSide = compileFinal "switch (side(param [0, player, [objNull]])) do 
{
    case civilian: {'civilian'};
    case west:{'west'};
    case east:{'east'};
    case independent:{'independent'};
    default{'unknown'};
}";
publicVariable "life_fnc_getPlayerSide";
```

I thought i commented it out to be fair. sorry

**Comment by Ni1kko** [comment]
https://github.com/Ni1kko/Framework/invitations

**Comment by Ni1kko** [comment]
Added again... https://github.com/Ni1kko/Framework/commit/c367996c56b5b476a0ad2ef3e028b53eaf17bc2f
