### ISSUE TITLE
error fn_configuration

### ISSUE THREAD

**Issue by VanilleIce** [Ni1kko/FrameworkV2#15]
12:24:13 Error in expression <
missionNamespace setVariable [_varName,_varValue];
}else{
_variablesFlagged pus>
12:24:13   Error position: <_varValue];
}else{
_variablesFlagged pus>
12:24:13   Error Undefined variable in expression: _varvalue
12:24:13 File \OsbornTV\mpmissions\Altis_Life.Altis\core\fn_configuration.sqf..., line 128

**Comment by Ni1kko** [comment]
Fixed it think.... https://github.com/Ni1kko/Framework/commit/6ee54123cf184936fe1c9acfe893439bb718e8ed

**Comment by Ni1kko** [comment]
If you need me to fix something quicker, or want to talk about the framework DM me on discord :) Ni1kko#1150

**Comment by Ni1kko** [comment]
I have tested framework and confirm that issue is now resolved :)
